# This config file contains the list of patches 
# to be applied by callisto during the build

# Add as many as you like!

[resources]
patches = [
    "resources/patches/bwram_plus-v1.3/bwram_plus.asm",
    "resources/patches/retry-v2.06c/retry.asm",
]
